<?php
/**
 * Implementation of hook_install()
 */
function commerce_stock_install() {
  $config = [
    'type' => 'inline_entity_form_simple',
    'weight' => 2,
    'settings' => [
      'override_labels' => FALSE,
      'label_singular' => '',
      'label_plural' => '',
    ],
    'third_party_settings' => [],
  ];

  \Drupal::configFactory()
    ->getEditable('core.entity_form_display.commerce_product_variation.default.default')
    ->set('content.field_stock', $config)
    ->save();
}
